League.create(league_name: "Premier League", league_country: "England & Wales")
League.create(league_name: "Serie A", league_country: "Italy")
League.create(league_name: "La Liga", league_country: "Spain")
League.create(league_name: "Bundisliga", league_country: "Germany")
League.create(league_name: "Major League Soccer", league_country: "United States & Canada")
